Hw1
Genateep/homework_repository pull request #1
Opened 2021-11-15 23:31 UTC by Genateep

2021-11-16 21:05 UTC, nikitosboroda requested changes

2021-11-16 21:05 UTC, icanhardcode commented on .github/workflows/main.yml
> +          py.test homework1/tests
are u going to add rows like that for others HWs? return previous version pls

2021-11-16 21:05 UTC, icanhardcode commented on homework1/task02.py
> +def check_fib(data: Sequence[int]) -> bool:
let it be the fibb sequence if length of data >= 3

2021-11-16 21:05 UTC, icanhardcode commented on homework1/task03.py
> +                nums.update(map(int, line.split()))
```set.add()```

2021-11-16 21:05 UTC, icanhardcode commented on homework1/task03.py
> +    """Returns a tuple with the max and min values"""
check the docstring and func's name.. and watch what u return

2021-11-16 21:05 UTC, icanhardcode commented on homework1/tests/test_task02.py
> +
try to think.. are there any corner cases?

2021-11-16 21:05 UTC, icanhardcode commented on homework1/tests/test_task03.py
> +@pytest.mark.parametrize(
u dont need parametrize if u have only one test

2021-11-16 21:05 UTC, nikitosboroda commented on homework1/tests/test_task05.py
> +
negative cases?

2021-11-17 18:01 UTC, Genateep commented on homework1/task03.py
> +    """Returns a tuple with the max and min values"""
"For example for [1, 2, 3, 4, 5], function should return [1, 5]"  I took this example to work. But yes, it contradicts the title for me. Swapped the values

2021-11-17 18:01 UTC, Genateep commented on homework1/tests/test_task02.py
> +
tried... could you throw a hint?

2021-12-07 20:56 UTC, nikitosboroda reviewed
corner cases for fibbonachi task: hint- [1] - is it a fibb seq?

2021-12-12 09:50 UTC, merged